// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreateTime           int64    `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	StartTime            int64    `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	FinishTime           int64    `protobuf:"varint,6,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	ExitCode             int64    `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ImageRepo            string   `protobuf:"bytes,8,opt,name=image_repo,json=imageRepo,proto3" json:"image_repo,omitempty"`
	ImageTag             string   `protobuf:"bytes,9,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	Cpus                 int64    `protobuf:"varint,10,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Gpus                 int64    `protobuf:"varint,11,opt,name=gpus,proto3" json:"gpus,omitempty"`
	Memory               int64    `protobuf:"varint,12,opt,name=memory,proto3" json:"memory,omitempty"`
	OwnerName            string   `protobuf:"bytes,13,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	OwnerQid             string   `protobuf:"bytes,14,opt,name=owner_qid,json=ownerQid,proto3" json:"owner_qid,omitempty"`
	OwnerEmail           string   `protobuf:"bytes,15,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"`
	Node                 string   `protobuf:"bytes,16,opt,name=node,proto3" json:"node,omitempty"`
	ContainerId          string   `protobuf:"bytes,17,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	FileUri              string   `protobuf:"bytes,18,opt,name=file_uri,json=fileUri,proto3" json:"file_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Task) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Task) GetFinishTime() int64 {
	if m != nil {
		return m.FinishTime
	}
	return 0
}

func (m *Task) GetExitCode() int64 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *Task) GetImageRepo() string {
	if m != nil {
		return m.ImageRepo
	}
	return ""
}

func (m *Task) GetImageTag() string {
	if m != nil {
		return m.ImageTag
	}
	return ""
}

func (m *Task) GetCpus() int64 {
	if m != nil {
		return m.Cpus
	}
	return 0
}

func (m *Task) GetGpus() int64 {
	if m != nil {
		return m.Gpus
	}
	return 0
}

func (m *Task) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Task) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

func (m *Task) GetOwnerQid() string {
	if m != nil {
		return m.OwnerQid
	}
	return ""
}

func (m *Task) GetOwnerEmail() string {
	if m != nil {
		return m.OwnerEmail
	}
	return ""
}

func (m *Task) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *Task) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *Task) GetFileUri() string {
	if m != nil {
		return m.FileUri
	}
	return ""
}

type TaskShortForm struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ImageRepo            string   `protobuf:"bytes,3,opt,name=image_repo,json=imageRepo,proto3" json:"image_repo,omitempty"`
	ImageTag             string   `protobuf:"bytes,4,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	CreateTime           int64    `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	StartTime            int64    `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	FinishTime           int64    `protobuf:"varint,7,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	ExitCode             int64    `protobuf:"varint,8,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	OwnerName            string   `protobuf:"bytes,9,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskShortForm) Reset()         { *m = TaskShortForm{} }
func (m *TaskShortForm) String() string { return proto.CompactTextString(m) }
func (*TaskShortForm) ProtoMessage()    {}
func (*TaskShortForm) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *TaskShortForm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskShortForm.Unmarshal(m, b)
}
func (m *TaskShortForm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskShortForm.Marshal(b, m, deterministic)
}
func (m *TaskShortForm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskShortForm.Merge(m, src)
}
func (m *TaskShortForm) XXX_Size() int {
	return xxx_messageInfo_TaskShortForm.Size(m)
}
func (m *TaskShortForm) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskShortForm.DiscardUnknown(m)
}

var xxx_messageInfo_TaskShortForm proto.InternalMessageInfo

func (m *TaskShortForm) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TaskShortForm) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TaskShortForm) GetImageRepo() string {
	if m != nil {
		return m.ImageRepo
	}
	return ""
}

func (m *TaskShortForm) GetImageTag() string {
	if m != nil {
		return m.ImageTag
	}
	return ""
}

func (m *TaskShortForm) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *TaskShortForm) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *TaskShortForm) GetFinishTime() int64 {
	if m != nil {
		return m.FinishTime
	}
	return 0
}

func (m *TaskShortForm) GetExitCode() int64 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *TaskShortForm) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

type Tasks struct {
	Tasks                []*TaskShortForm `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Tasks) Reset()         { *m = Tasks{} }
func (m *Tasks) String() string { return proto.CompactTextString(m) }
func (*Tasks) ProtoMessage()    {}
func (*Tasks) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *Tasks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tasks.Unmarshal(m, b)
}
func (m *Tasks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tasks.Marshal(b, m, deterministic)
}
func (m *Tasks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tasks.Merge(m, src)
}
func (m *Tasks) XXX_Size() int {
	return xxx_messageInfo_Tasks.Size(m)
}
func (m *Tasks) XXX_DiscardUnknown() {
	xxx_messageInfo_Tasks.DiscardUnknown(m)
}

var xxx_messageInfo_Tasks proto.InternalMessageInfo

func (m *Tasks) GetTasks() []*TaskShortForm {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type Option struct {
	Limit                uint32   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	OwnerName            string   `protobuf:"bytes,3,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Option) Reset()         { *m = Option{} }
func (m *Option) String() string { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()    {}
func (*Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{3}
}

func (m *Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option.Unmarshal(m, b)
}
func (m *Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option.Marshal(b, m, deterministic)
}
func (m *Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option.Merge(m, src)
}
func (m *Option) XXX_Size() int {
	return xxx_messageInfo_Option.Size(m)
}
func (m *Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Option proto.InternalMessageInfo

func (m *Option) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Option) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Option) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

type Requirement struct {
	Cpus                 int64    `protobuf:"varint,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Gpus                 int64    `protobuf:"varint,2,opt,name=gpus,proto3" json:"gpus,omitempty"`
	Memory               int64    `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Requirement) Reset()         { *m = Requirement{} }
func (m *Requirement) String() string { return proto.CompactTextString(m) }
func (*Requirement) ProtoMessage()    {}
func (*Requirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{4}
}

func (m *Requirement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requirement.Unmarshal(m, b)
}
func (m *Requirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requirement.Marshal(b, m, deterministic)
}
func (m *Requirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requirement.Merge(m, src)
}
func (m *Requirement) XXX_Size() int {
	return xxx_messageInfo_Requirement.Size(m)
}
func (m *Requirement) XXX_DiscardUnknown() {
	xxx_messageInfo_Requirement.DiscardUnknown(m)
}

var xxx_messageInfo_Requirement proto.InternalMessageInfo

func (m *Requirement) GetCpus() int64 {
	if m != nil {
		return m.Cpus
	}
	return 0
}

func (m *Requirement) GetGpus() int64 {
	if m != nil {
		return m.Gpus
	}
	return 0
}

func (m *Requirement) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func init() {
	proto.RegisterType((*Task)(nil), "types.Task")
	proto.RegisterType((*TaskShortForm)(nil), "types.TaskShortForm")
	proto.RegisterType((*Tasks)(nil), "types.Tasks")
	proto.RegisterType((*Option)(nil), "types.Option")
	proto.RegisterType((*Requirement)(nil), "types.Requirement")
}

func init() {
	proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff)
}

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x95, 0xa6, 0x69, 0x9b, 0x97, 0x75, 0x80, 0x55, 0x21, 0x23, 0x84, 0x56, 0x7a, 0xaa,
	0x38, 0xf4, 0xc0, 0x3e, 0x02, 0x02, 0x89, 0x03, 0x20, 0x42, 0x77, 0x8e, 0x4c, 0xf2, 0xda, 0x3d,
	0xad, 0x8e, 0x33, 0xdb, 0x15, 0xec, 0x4b, 0xf0, 0x75, 0xb9, 0x22, 0x3f, 0x57, 0x53, 0x17, 0xa6,
	0x6d, 0x37, 0xbf, 0xdf, 0x3f, 0xb6, 0x5f, 0xfe, 0xef, 0x6f, 0x00, 0xaf, 0xdc, 0xd5, 0xaa, 0xb3,
	0xc6, 0x1b, 0x91, 0xf9, 0x9b, 0x0e, 0xdd, 0xe2, 0x6f, 0x0a, 0xc3, 0xb5, 0x72, 0x57, 0xe2, 0x14,
	0x06, 0xd4, 0xc8, 0x64, 0x9e, 0x2c, 0xa7, 0xe5, 0x80, 0x1a, 0x31, 0x83, 0xcc, 0x93, 0xdf, 0xa1,
	0x1c, 0xcc, 0x93, 0x65, 0x5e, 0xc6, 0x42, 0xcc, 0xa1, 0x68, 0xd0, 0xd5, 0x96, 0x3a, 0x4f, 0xa6,
	0x95, 0x29, 0x6b, 0xc7, 0x48, 0x9c, 0x41, 0x51, 0x5b, 0x54, 0x1e, 0x2b, 0x4f, 0x1a, 0xe5, 0x70,
	0x9e, 0x2c, 0xd3, 0x12, 0x22, 0x5a, 0x93, 0x46, 0xf1, 0x06, 0xc0, 0x79, 0x65, 0x7d, 0xd4, 0x33,
	0xd6, 0x73, 0x26, 0x2c, 0x9f, 0x41, 0xb1, 0xa1, 0x96, 0xdc, 0x65, 0xd4, 0x47, 0x71, 0x7f, 0x44,
	0xfc, 0xc1, 0x6b, 0xc8, 0xf1, 0x37, 0xf9, 0xaa, 0x36, 0x0d, 0xca, 0x31, 0xcb, 0x93, 0x00, 0x3e,
	0x98, 0x86, 0x0f, 0x27, 0xad, 0xb6, 0x58, 0x59, 0xec, 0x8c, 0x9c, 0x70, 0x7b, 0x39, 0x93, 0x12,
	0x3b, 0x13, 0xf6, 0x46, 0xd9, 0xab, 0xad, 0xcc, 0x59, 0x9d, 0x30, 0x58, 0xab, 0xad, 0x10, 0x30,
	0xac, 0xbb, 0xbd, 0x93, 0xc0, 0x67, 0xf2, 0x3a, 0xb0, 0x6d, 0x60, 0x45, 0x64, 0x61, 0x2d, 0x5e,
	0xc2, 0x48, 0xa3, 0x36, 0xf6, 0x46, 0x9e, 0x30, 0x3d, 0x54, 0xe1, 0x6e, 0xf3, 0xab, 0x45, 0x5b,
	0xb5, 0x4a, 0xa3, 0x9c, 0xc6, 0xbb, 0x99, 0x7c, 0x55, 0xb1, 0xef, 0x28, 0x5f, 0x53, 0x23, 0x4f,
	0xe3, 0xdd, 0x0c, 0xbe, 0x53, 0x13, 0xfe, 0x3a, 0x8a, 0xa8, 0x15, 0xed, 0xe4, 0x33, 0x96, 0xe3,
	0x71, 0x1f, 0x03, 0x09, 0x8d, 0xb4, 0xe1, 0x87, 0x9f, 0xb3, 0xc2, 0x6b, 0xf1, 0x16, 0x4e, 0x6a,
	0xd3, 0x7a, 0x45, 0x61, 0x23, 0x35, 0xf2, 0x45, 0x9c, 0xc6, 0x2d, 0xfb, 0xdc, 0x88, 0x57, 0x30,
	0xd9, 0xd0, 0x0e, 0xab, 0xbd, 0x25, 0x29, 0x58, 0x1e, 0x87, 0xfa, 0xc2, 0xd2, 0xe2, 0xcf, 0x00,
	0xa6, 0x61, 0xf2, 0x3f, 0x2e, 0x8d, 0xf5, 0x9f, 0x8c, 0xd5, 0x4f, 0x8c, 0xc0, 0x5d, 0x8b, 0xd3,
	0x07, 0x2d, 0x1e, 0xf6, 0x2c, 0xee, 0x85, 0x23, 0x7b, 0x24, 0x1c, 0xa3, 0x47, 0xc2, 0x31, 0x7e,
	0x38, 0x1c, 0x93, 0xff, 0xc3, 0x71, 0x34, 0xa0, 0xbc, 0x37, 0xa0, 0xc5, 0x39, 0x64, 0xc1, 0x0f,
	0x27, 0xde, 0x41, 0x16, 0x1e, 0x8a, 0x93, 0xc9, 0x3c, 0x5d, 0x16, 0xef, 0x67, 0x2b, 0x7e, 0x2a,
	0xab, 0x3b, 0x66, 0x95, 0xf1, 0x93, 0xc5, 0x05, 0x8c, 0xbe, 0xc5, 0xe0, 0xcf, 0x20, 0xdb, 0x91,
	0x26, 0x7f, 0x30, 0x30, 0x16, 0x21, 0x2c, 0x66, 0xb3, 0x71, 0xe8, 0xd9, 0xc4, 0x69, 0x79, 0xa8,
	0x7a, 0xbd, 0xa4, 0xfd, 0x5e, 0xbe, 0x40, 0x51, 0xe2, 0xf5, 0x9e, 0x2c, 0x6a, 0x6c, 0xfd, 0x6d,
	0x34, 0x93, 0x7b, 0xa2, 0x39, 0xb8, 0x37, 0x9a, 0xe9, 0x71, 0x34, 0x7f, 0x8e, 0xf8, 0xcd, 0x9f,
	0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x19, 0x8b, 0x8f, 0x9b, 0x01, 0x04, 0x00, 0x00,
}
